### ISSUE TITLE
Updating read.me with links to git/GitHub training

### ISSUE THREAD

**Issue by DarrenfJ** [RomchyFCC/collaborative_effort#1]
the P1xt guides (link: https://github.com/P1xt/p1xt-guides )

have an FAQ with some great links to git and GitHub training. I think if we're attracting new people to play around here it would be nice to have some information around using the tool.

FAQ: https://github.com/P1xt/p1xt-guides/blob/master/faq.md

**Comment by RomchyFCC** [comment]
I would love it if you do this one, I can't make it fit well with the contributions doc

**Comment by DarrenfJ** [comment]
OK, maybe add a folder just for a read.me that is a linkFarm for supporting docs and training for anyone who wants to contribute?

**Comment by RomchyFCC** [comment]
Since this issue and the 2nd issue are the same I closed this one and continued the dialogue there

**Comment by DarrenfJ** [comment]
awesome, thanks man.

D
