### ISSUE TITLE
Add to read.me links to free markdown training

### ISSUE THREAD

**Issue by DarrenfJ** [RomchyFCC/collaborative_effort#2]
Similar to the last issue ( https://github.com/RomchyFCC/collaborative_effort/issues/1 ) we could add some links to markdown tutorials.

**Comment by RomchyFCC** [comment]
I suggest the shay howe html and css tutorial, well written guide, thoughts?

**Comment by RomchyFCC** [comment]
is that what you had in mind?

if you have any guides you can freely add them

**Comment by DarrenfJ** [comment]
Yah.. I think as a 'project' this repo should be us building a website that
helps others build their own projects specifically to learn GitHub as well..

It's a bit *meta* a project about project to build this exact project.. but
really the best purporse of this could be to create something that give an
initial guide and links to DIYing this same idea for others..

**Comment by DarrenfJ** [comment]
from issue 1:

the P1xt guides (link: https://github.com/P1xt/p1xt-guides )

have an FAQ with some great links to git and GitHub training. I think if we're attracting new people to play around here it would be nice to have some information around using the tool.

FAQ: https://github.com/P1xt/p1xt-guides/blob/master/faq.md

Markdown tutorials:

https://www.markdowntutorial.com/

http://commonmark.org/help/tutorial/

markdown guides

https://daringfireball.net/projects/markdown/basics

https://guides.github.com/features/mastering-markdown/

**Comment by DarrenfJ** [comment]
I'm looking at how it's done here: https://github.com/P1xt/p1xt-guides

and it's a series of fileName.md markdown files that are linked.. I can set something up like that for training/learning links

**Comment by DarrenfJ** [comment]
Also noticed when I updated my fork that you already added the folder and markdown.. so might just add these in as a Pull request from my own repo...

**Comment by RomchyFCC** [comment]
You should totally add these as a PR so we find out if it works or not.

We put the "cheat sheets" in one folder and guides in the other, right now they are both in the same file.

**Comment by RomchyFCC** [comment]
Ok so this is done, what else should we do now on the whole scale idea?

Should we get down to coding aswell?

So far this has been on the back burner on my side

**Comment by DarrenfJ** [comment]
I think we can use issues and the Project trello board to map out how we
want the code to expand. I'm envisioning some sort of thing that allows you
to set up your own repo, the walks you through a series of steps to start
building a site that is a mirror of this site...

the details of each step are a learning process to using git/GitHub.

Something along the lines of this.. where the guide is actually making you
do a PR... https://guides.github.com/activities/forking/

But more from start to finish.. forking, issues, using git and command
line.. and more akin to the flavour of fCC where you are not so much
*reading* and then clicking links to do it but doing it in an app or
something..

i dunno yet.. just spitballing it for now

**Comment by RomchyFCC** [comment]
Ok, I have some thoughts on that, we can make a website, where everyone would start with just writing their name in the file or their username. It would be a webpage or just a comment, I don't mind either way, we don't need something professional or working, as long as the main code doesn't break and it displays all the names, we are good to go. It would also be good to scale to infinity, the more users the more merge conflicts, pull requests and so on so on. What do you think? We could also then create ranks of when the contributor joined or when a pull request was made :D 
Of course we could also list some guides or write them for that matter on how to contribute in a fast and easy way. A TLDR of the readme...

**Comment by DarrenfJ** [comment]
Sounds like a good place to start as any...

**Comment by RomchyFCC** [comment]
ok, will start working on a prototype as soon as i'm done with my scheduled designs, I see you made 2 of these your project, is that the project "trello board" you were talking about :O?

**Comment by DarrenfJ** [comment]
Yah, they're just projects but they're not assigned to anybody yet.

I've used trello before ( https://trello.com/ ) and the project section of
GitHub has a very similar feel to it..

Issues can be tracked as a 'card' in a project, but also you can just
create cards separately as their own thing.. Allows you/me to track a to-do
list in a very much more dynamic way.
