### ISSUE TITLE
updating read.me to make it more inviting

### ISSUE THREAD

**Issue by DarrenfJ** [RomchyFCC/collaborative_effort#3]
don't have specifics but I know in some of the Open Source discussions in the fCC forums, people had tips and tricks for helping newbie coders contribute.

leaving this link here. Will explore and add issues/next steps as I go

https://forum.freecodecamp.org/search?q=open%20source

**Comment by DarrenfJ** [comment]
this is the link to forum for some ideas on how to make it more inviting...

(thanks JacksonBates https://github.com/JacksonBates )

https://forum.freecodecamp.org/t/join-an-open-source-community/161163/10

**Comment by RomchyFCC** [comment]
ok, added the contributions page, thanks!
